#KDIR := /lib/modules/$(shell uname -r)/build
all:
	$(CC) -o usermmap usermmap.c

clean:
	rm -rf usermmap
#%.ko: %.o
#(KDIR) SUBDIRS=$(PWD) $@
#
#kernel_modules:
#(KDIR) SUBDIRS=$(PWD) modules
#gcc test.c -o test
#
#clean:
#(KDIR) SUBDIRS=$(PWD) clean
#rm -f test


